name: CDPROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
          docker pull sruthilayagadila/dev-task-master:latest
          docker tag sruthilayagadila/dev-task-master:latest sruthilayagadila/prod-task-master:latest
          docker push sruthilayagadila/prod-task-master:latest
    - name: Kubectl Action
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG_PROD }}
    - run: |
          kubectl apply -f deployment-service.yml
